### ISSUE TITLE
issue about QtCore.QString

### ISSUE THREAD

**Issue by consultit** [makehumancommunity/community-plugins-assetdownload#10]
In my GNU/Linux box (Debian 9) I installed this plugin in the source tree of [makehuman](https://bitbucket.org/MakeHuman/makehuman). When executing makehuman I got some of this errors:
```
...
Traceback (most recent call last):
  File "plugins/8_asset_downloader/tablemodel.py", line 91, in headerData
    return QtCore.QString(self.__headers[section])
AttributeError: 'module' object has no attribute 'QString'
...
```
and the table of available assets was completely blank. Then I replaced `QtCore.QString` with `str` and so the problem is solved.
Bye

**Comment by joepal1976** [comment]
Thanks. Yes, this is an obvious bug. 

I'll see to committing an update tomorrow.

**Comment by joepal1976** [comment]
Fixed in https://github.com/makehumancommunity/community-plugins-assetdownload/commit/0ba18d6b7449f6902cbbe6f8508c9f00037a5d5e

I tested this on both py2/pyside and py3/pyqt5, but it'd be helpful if you tested this on your side too. 

If it still doesn't work, please specify which version of pyqt you're using, and exactly which source version of makehuman you're using.
