### ISSUE TITLE
Downloading multiple items at once not working.

### ISSUE THREAD

**Issue by ZeroCool940711** [makehumancommunity/community-plugins-assetdownload#13]
For what I can see you can select multiple items by pressing ctr+click or shift+click but when you press the download button only one of the items is downloaded, would be nice to be able to download multiple items at the same time, it would make things a lot easier and save a lot of time. Thanks for the time.

**Comment by joepal1976** [comment]
There are very good reasons for not allowing this. The load on the servers hosting the online repos is bordering on overwhelming as it is. Allowing multiple downloads will only encourage people to mark large blocks of assets and download them all in case they might be interesting.

Until such a point where we have unlimited bandwidth for a cost within our budget, the fix here will be to change the selection mode so that only one item can be selected at a time. 

This way, people have to go through the effort of explicitly picking those items they want, meaning the server load will at least be distributed over a longer period of time.

**Comment by ZeroCool940711** [comment]
I dont see why this would be a problem, the server will be even slower and getting more requests as it is now, for example, I do want to get a lot of assets that I already know I will use, I have to select one item, then click download, because I have selected the filter option to show only assets that I havent downloaded yet and because it doesnt remove the items automatically from the table of available assets I have to click update list, it doesnt remove the item yet so I have to click synchronize to requests the changes to the list from the server and then click again on update to remove it from there, also making it so you can select multiple items and queue them to be downloaded but downloading only one at the time would be a better solution and a more useful way to do it. As it is right now its pretty annoying and is makign more requests to the servers.
