### ISSUE TITLE
Asset downloader fails to import with "PySide is not defined" error

### ISSUE THREAD

**Issue by stuartlangridge** [makehumancommunity/community-plugins-assetdownload#28]
Running makehuman v1.1.1 on Ubuntu 18.04, when I add this plugin it fails to import. The line failing is
https://github.com/makehumancommunity/community-plugins-assetdownload/blob/34cc1a485b1cdf5134440be4e79fa34a7e59d630/8_asset_downloader/assetdownload.py#L53

with error

```
Could not load 8_asset_downloader
Traceback (most recent call last):
  File "./core/mhmain.py", line 530, in loadPlugin
    module = imp.load_module(name, fp, pathname, description)
  File "plugins/8_asset_downloader/__init__.py", line 30, in <module>
    from .assetdownload import AssetDownloadTaskView
  File "plugins/8_asset_downloader/assetdownload.py", line 53, in <module>
    QtWidgets = PySide.Qt.QtWidgets
NameError: name 'PySide' is not defined
```

and I'm a little puzzled how this ever works since the code doesn't import PySide by itself at all (and that's why there's a NameError). Is there anything I can do to resolve this?

**Comment by Aranuvir** [comment]
It does import Pyside, when it is available on your system (see lines above). The code is somewhat unfortunate here, because it does not  prevent a conflicting mixture between Pyside and PyQt. Technically you can try to fix the plugin, but it'll be somewhat cumbersome in case MakeHuman was installed via ppa and could also lead to inconsistency in your package management.
There is no reason we you shouldn't upgrade to a recent version of MH. You can either run from source or install via ppa. Good luck.

**I'll leave this issue open, though the correct topic would be: remove old code from the plugins.**

**Comment by stuartlangridge** [comment]
@Aranuvir as I understand it, there isn't a newer version in the PPA? https://launchpad.net/~makehuman-official/+archive/ubuntu/makehuman-11x has 1.1.1 and that's all (which is what I installed). I'd be happy to run the newer version as the MH website suggests but it seems there are only Windows downloads for it. (Otherwise I would have tried to fix the plugin, of course.)

**Comment by joepal1976** [comment]
You're using the old PPA. The 1.2.x PPA is https://launchpad.net/~makehuman-official/+archive/ubuntu/makehuman-community

The last release there was made a few days ago. 

But looking at the download page I see why you ended up where you did, as the download page still points at the old site. My bad. I'll fix this too.

**Comment by stuartlangridge** [comment]
@joepal1976 thank you very much; I was using the old version, now I'm not, and everything works fine in the new PPA, so thank you for that! (You may want to take a look at snaps so there's only one version which works everywhere, but the PPA is working fine for me for now! Many thanks.)
