### ISSUE TITLE
Multiple Row Selection for Assets

### ISSUE THREAD

**Issue by christopwner** [makehumancommunity/community-plugins-assetdownload#31]
This is a feature request for multiple row selection in the community asset page for downloading multiple items at a time.

Using release HEAD b32df8d

**Comment by christopwner** [comment]
@Aranuvir mentioned there might be some concern regarding rate limited in the ticket i originally posted: makehumancommunity/makehuman/issues/110

I'd assume these would be handled serverside through a balancer or IP tables rules.

**Comment by Aranuvir** [comment]
Quote:
>I'd assume these would be handled serverside through a balancer or IP tables rules.

This is mainly handled via the internet service subscriber's wallet.

**Comment by joepal1976** [comment]
The problem isn't rate, the problem is total traffic quota. I pay for 3TB worth of downloads per month, which is the plan that can be afforded with the current income from patreon. This cap includes pretty much everything (forum, wiki, site...) except the release binaries which have been outsourced to tuxfamily.

The asset repo is up towards 20gb large. 

From experience: if it's easy to do so, a lot of people will try to download everything and then delete what they don't like. This would rapidly make the traffic crash through the quota roof.

Thus I've implemented a very soft limit: you can download whatever you want, but you'll have to do it item per item. Currently, this is enough to keep the total traffic below the monthly quota.

So until such a time when the patreon income grows large enough to support more traffic, the item-per-item thing is per design and not something that will be changed.
